imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services/default.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:            ~
    translator:
        fallback: ["%locale%"]
        paths:
            - '%kernel.root_dir%/res/translations'
    secret:          "%secret%"
    router:
        resource: "/app/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    #validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "3306"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
            engine: InnoDB

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            entity:
                type: yml
                dir: "%kernel.root_dir%/res/config/doctrine/entity"
                prefix: App\Entity
                alias: Entity
                is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# FrameworkExtra Configuration
sensio_framework_extra:
    router:
        annotations: false
    view:
        annotations: false
    cache:
        annotations: false
    security:
        annotations: false
